parameters:
  session.storage.options:
    {
      gc_probability: 1,
      gc_divisor: 100,
      gc_maxlifetime: 200000,
      cookie_lifetime: 2000000,
    }
  twig.config: { debug: false, auto_reload: false, cache: true }
  renderer.config:
    {
      required_cache_contexts:
        ["languages:language_interface", theme, user.permissions],
      auto_placeholder_conditions:
        { max-age: 0, contexts: [session, user], tags: {} },
    }
  http.response.debug_cacheability_headers: false
  factory.keyvalue: {}
  factory.keyvalue.expirable: {}
  filter_protocols:
    [
      http,
      https,
      ftp,
      news,
      nntp,
      tel,
      telnet,
      mailto,
      irc,
      ssh,
      sftp,
      webcal,
      rtsp,
    ]
  # Configure Cross-Site HTTP requests (CORS).
  # Read https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS
  # for more information about the topic in general.
  # Note: By default the configuration is disabled.
  cors.config:
    enabled: true
    # Specify allowed headers, like 'x-allowed-header'.
    allowedHeaders:
      [
        "x-csrf-token",
        "authorization",
        "content-type",
        "accept",
        "origin",
        "x-requested-with",
        "access-control-allow-origin",
        "x-allowed-header",
        "*",
      ]
    # Specify allowed request methods, specify ['*'] to allow all possible ones.
    allowedMethods: ["*"]
    # Configure requests allowed from specific origins.
    allowedOrigins: ["*"]
    # Sets the Access-Control-Expose-Headers header.
    exposedHeaders: false
    # Sets the Access-Control-Max-Age header.
    maxAge: false
    # Sets the Access-Control-Allow-Credentials header.
    supportsCredentials: true
