# The routes of the project.
#
# Each route describes how an incoming URL is going
# to be processed by Platform.sh.

"https://{default}/":
  type: upstream
  upstream: "app:http"

"https://www.{default}/":
  type: redirect
  to: "https://{default}/"

"https://api.{default}/":
  type: upstream
  upstream: "api:http"
  cache:
    enabled: true
    default_ttl: 0
    cookies: ["*"]
    headers: ["Accept", "Accept-Language"]
