# This file describes an application. You can have multiple applications
# in the same project.

# The name of this app. Must be unique within a project.
name: api

# The runtime the application uses.
type: "php:7.2"

# Configuration of the build of this application.
build:
  flavor: composer

# The build-time dependencies of the app.
dependencies:
  php:
    "drush/drush": "^8.0"
    "drupal/console": "@stable"

# The relationships of the application with services or other applications.
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form `<service name>:<endpoint name>`.
relationships:
  database: "mysqldb:mysql"
#    solr: "solr:solr"
#    redis: "redis:redis"

# The configuration of app when it is exposed to the web.
web:
  # Specific parameters for different URL prefixes.
  locations:
    "/":
      # The folder to serve static assets for this location from.
      # (Relative to the application root.)
      root: "html"

      # How long to allow static assets from this location to be cached.
      # (Can be a time or -1 for no caching. Times can be suffixed with
      # "ms" (milliseconds), "s" (seconds), "m" (minutes), "h" (hours),
      # "d" (days), "w" (weeks), "M" (months, 30d) or "y" (years, 365d).)
      expires: -1

      # Whether to forward disallowed and missing resources from this
      # location to the application.
      # (Can be true, false or a URI path string.)
      passthru: "/index.php"

      # Deny access to static files in this location.
      allow: false

      # Rules for specific URI patterns.
      rules:
        # Allow access to common static files.
        '\.(jpe?g|png|gif|svgz?|css|js|map|ico|bmp|eot|woff2?|otf|ttf)$':
          allow: true
        '^/robots\.txt$':
          allow: true
        '^/sitemap\.xml$':
          allow: true

    "/sites/default/files":
      # Allow access to all files in the public files directory.
      allow: true
      expires: 5m
      passthru: "/index.php"
      root: "html/sites/default/files"

      # Do not execute PHP scripts.
      scripts: false

      rules:
        # Provide a longer TTL (2 weeks) for aggregated CSS and JS files.
        "^/sites/default/files/(css|jss)":
          expires: 2w

    "/profiles/contrib/social/themes/"
      # Allow access to all files in the themes directory
      allow: true
      headers:
        Access-Control-Allow-Origin: "*"

# The size of the persistent disk of the application (in MB).
disk: 2048

# The mounts that will be performed when the package is deployed.
mounts:
  "/html/sites/default/files": "shared:files/files"
  "/tmp": "shared:files/tmp"
  "/private": "shared:files/private"
  "/log": "shared:files/log"

# The hooks executed at various points in the lifecycle of the application.
hooks:
  # We run deploy hook after your application has been deployed and started.
  # @TODO Re-import configuration
  deploy: |
    cd html
    php -r 'opcache_reset();'
    drush -y cache-rebuild
    drush -y updatedb
    drush cc drush
    drush -y fra --bundle=social
    drush -y en rfe_orchestrator
    drush cc drush
    drush -y fra --bundle=rfe
    drush -y entup

    if [ $PLATFORM_BRANCH != "master" ]; then
      drush -y pm-enable rfe_helper
      drush -y enterprise-sanitize
      drush -y pm-enable social_demo
      drush sda enterprise_test_user
      drush -y pm-uninstall social_demo
      drush -y pm-uninstall rfe_helper
      drush -y pm-uninstall enterprise_helper
      drush -y pm-uninstall social_wootric
    fi

# The configuration of scheduled execution.
# @TODO Add more crons to make sure the stream is up to date.
crons:
  drupal_cron1:
    spec: "*/5 * * * *"
    cmd: "cd html ; drush core-cron"
#    renewcert:
#        # To ensure that a Let's encrypt certificate is never older than 2 weeks force
#        # a redeploy at 1 am (UTC) (3 am CEST) on the 1st and 15th of every month.
#        # Remove this cronjob if you set-up a custom SSL certificate because it has no
#        # use in that case. See: https://docs.platform.sh/configuration/routes/https.html#automatic-certificate-renewal
#        spec: '0 1 1,15 * *'
#        cmd: |
#            if [ "$PLATFORM_BRANCH" = master ]; then
#                platform redeploy --yes --no-wait
#            fi
