version: "2"

services:
  web:
    image: goalgorilla/open_social_docker:dev
    volumes:
      - ./:/var/www
    links:
      - db
      - mailcatcher
    environment:
      - VIRTUAL_HOST=rfe.localhost
      - DRUPAL_SETTINGS=development
    ports:
      - "80"
    network_mode: "bridge"
    container_name: social_rfe_web

  db:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=social
    volumes:
      - db_data_rfe_enterprise:/var/lib/mysql
    ports:
      - "3306"
    network_mode: "bridge"
    container_name: social_rfe_db
    command: mysqld --max_allowed_packet=16M

  mailcatcher:
    image: schickling/mailcatcher
    environment:
      - VIRTUAL_HOST=mailcatcher.rfe.localhost
      - VIRTUAL_PORT=1080
    ports:
      - "1080"
    network_mode: "bridge"
    container_name: social_rfe_mailcatcher

  selenium:
    image: selenium/standalone-firefox-debug:2.48.2
    links:
      - web:web
    ports:
      - "4444"
      - "5900"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    network_mode: "bridge"
    container_name: social_rfe_selenium

  behat:
    image: goalgorilla/open_social_docker:dev
    volumes:
      - ./:/var/www
    links:
      - web:web
      - db:db
      - selenium:selenium
      - mailcatcher:mailcatcher
    environment:
      - DRUPAL_SETTINGS=development
    network_mode: "bridge"
    container_name: social_rfe_behat

  cron:
    image: goalgorilla/open_social_docker:cron
    volumes:
      - ./:/var/www
    links:
      - db
    environment:
      - DRUPAL_SETTINGS=development
    network_mode: "bridge"
    container_name: social_rfe_cron

volumes:
  db_data_rfe_enterprise:
